#!/bin/bash

#This line uses regex to help normalize the MAC address values (parses the input regardless of whether it uses colons, periods, or hypens):
OUI=$(echo ${1//[:.-]/} | tr "[a-f]" "[A-F]" | egrep -o "^[0-9A-F]{6}")

#This line searches the ieee.org published oui.txt document for the OUI associated to the provided MAC address:
lynx -dump http://standards-oui.ieee.org/oui/oui.txt | grep $OUI
